name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  chapel-run-function:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
      # env:
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: Install Python, pip, and Python libraries
        run: |
          apt-get update
          apt-get install software-properties-common
          add-apt-repository ppa:deadsnakes/ppa
          apt-get update
          apt-get install -y python3.13-full
          python3 --version
          python3 -m venv .venv
          source .venv/bin/activate
          which python
          python3 -m pip install --upgrade pip
          python3 -m pip --version

          pip3 install --no-cache-dir python3-pip
          pip3 install --no-cache-dir numpy 
          pip3 install --no-cache-dir torch 
          pip3 install --no-cache-dir torchvision
          pip3 install --no-cache-dir virtualenv
      - uses: actions/checkout@v4
      - name: Check for dockerenv file and Python version
        run: |
          ls /.dockerenv && echo Found dockerenv
          echo "No dockerenv"
          python3 --version || echo "Python not found!"
      - name: Compile example/vgg
        run: |
          (cd examples/vgg && chpl test.chpl -M ../../src -M ../../lib -o vgg && python3 dump_weights.py && python3 process_img.py imgs/frog.jpg && ./vgg imgs/frog.chdata)
      - name: Run correspondence tests
        run: |
          (cd test/correspondence && python3 correspondence.py) || echo "Wups! Correspondence bug or more likely test failure!"
      - name:
        run: |
          echo "Pau!"